from aBST import aBST

A = aBST(2)
print(A.AddKey(10))
print(A.AddKey(12))
print(A.AddKey(7))
print(A.AddKey(11))
print(A.AddKey(5))
print(A.AddKey(14))
print(A.AddKey(11))
print(A.AddKey(9))
print(A.AddKey(10))
print(A.AddKey(12))
print(A.AddKey(7))
print(A.AddKey(11))
print(A.AddKey(5))
print(A.AddKey(14))
print(A.AddKey(11))
print(A.AddKey(9))
print(A.Tree)
print(A.FindKeyIndex(245))
print(A.AddKey(226))